name: mapk11
channels:
  - conda-forge
  - bioconda
dependencies:
  - biobb_analysis==3.6.0
  - biobb_io==3.6.0
  - biobb_model==3.6.0
  - biobb_md==3.6.0
  - biobb_structure_utils
  - nb_conda_kernels
  - jupyterlab
  - plotly
  - nglview
  - simpletraj
  - conda